apiVersion: genval/genai/v1beta1
metadata:
  name: cel-config
llmSpec:
  model: GPT4
  assistant: cel
  apiKey: OPENAI_KEY
  userPrompt: ./user-prompts/cel-prompt.md
  maxTokens: 2048
  presencePenalty: 0.0
  frequencyPenalty: 0.0
  topP: 0.3
  temperature: 0.7
  output: ./output/cel-llmResponse.md
