apiVersion: genval/genai/v1beta1
metadata:
  name: rego-config
llmSpec:
  model: GPT4
  assistant: rego
  apiKey: OPENAI_KEY
  userPrompt: ./user-prompts/rego-prompt.md
  maxTokens: 2048
  presencePenalty: 0.0
  frequencyPenalty: 0.0
  topP: 0.3
  temperature: 0.7
  output: ./output/rego-llmResponse.md
